### PR TITLE
DM-31214: Pin dependencies

### PR DESCRIPTION
**Pull request by spenczar**
From #1 - this pins dependency versions with pip-tools.

### CODE REVIEW

**Review by jonathansick — CHANGES_REQUESTED** [review]
Neato. I hadn't gone so far as to use pip-sync, I'll be interested to see how you like it.

I also like the pre-commit hook on pip-compile. We've been doing it via a Make command thusfar, but a pre-commit hooks also adds some nice consistency. One thing I wonder about is the use-case of `pre-commit run --all-files` in CI; will that always bump the compiled dependencies? I'm putting a "request changes" on the review only because we might want to validate that the `lint` GitHub Actions job can avoid failing when the compiled dependencies are purposefully behind. I suppose you could have that lint command ignore the requirements files? Something to look at.

Lastly, I think you can drop the `install_requires` from `setup.cfg` now.

**Comment by spenczar** [comment]
Ah, you're probably right that this will run every time, and so it will fail the check if there are ever any new versions of any dependencies! That's a really good point. I'll have to think a bit about how to fix that.

**Comment by spenczar** [comment]
Okay, @jonathansick, I think https://github.com/lsst-dm/alert_database_server/pull/4/commits/1f72b9ec1b78bec6e7de656c755772b2831e5fce is a good resolution for the bug you mentioned - take a look. It skips the `pip-compile` hook when running against all files, and then _does_ run it but only if the `in` file has changed, and it runs against the right commit range, I think.

There's still a bit of a race involved. If you add a new dependency and correctly run pip-compile, and then you wait like 3 months to actually make a PR, then your deps may move on and leave you behind, and the CI check will fail. But I think that's reasonable.

**Review by jonathansick — APPROVED** [review]

**Comment by jonathansick** [comment]
This looks good. If it becomes an issue you might drop back to running `pip-compile` manually (like in a Makefile), but I'd be interested to see how this works.

**Pull request merged**
